/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Income_Expenditure_Management;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import connections.DB_Connect;
import inventory.ims;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author Kasun
 */
public class exp_manage extends javax.swing.JFrame {

    Connection conx = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    String thisyear,thisday,thismonth,dayoneone,test,test1;
    
    
    public void extendFrame(){
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int height = screenSize.height;
        int width = screenSize.width;
        this.getContentPane().setPreferredSize(new Dimension(width,height));
        this.pack();
    }
    
    public exp_manage() {
        initComponents();
        extendFrame();
        conx = DB_Connect.getConnection();
         mythread1 t = new mythread1();
            t.start();
      
        //table load
        btnservice.setVisible(false);
        currentDate();
        tableload();
        calprof();
    }
    
    public class mythread1 extends Thread{
    
        public void run(){
        
            while(true){

                
            setDate();
            
               
            try {
                
                this.sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(ims.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }}
    
    }
    
    
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lgTime = new javax.swing.JLabel();
        lgDate = new javax.swing.JLabel();
        stringDay = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        sdate11 = new com.toedter.calendar.JDateChooser();
        sdate12 = new com.toedter.calendar.JDateChooser();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        btnshowall1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        incometbl = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        sdate2 = new com.toedter.calendar.JDateChooser();
        sdate1 = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        examount = new javax.swing.JTextField();
        extype = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        exdescription = new javax.swing.JTextArea();
        exaddbutton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        exid = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        expdate = new com.toedter.calendar.JDateChooser();
        exupdatebutton = new javax.swing.JButton();
        exdeletebutton = new javax.swing.JButton();
        exclear = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        btninvenory = new javax.swing.JButton();
        btnservice = new javax.swing.JButton();
        btnshowall = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        exptable = new javax.swing.JTable();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        invtable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        sdate9 = new com.toedter.calendar.JDateChooser();
        sdate10 = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        cancelprofit = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jobcostlbl = new javax.swing.JLabel();
        itemcostlbl = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        totalincomelbl = new javax.swing.JLabel();
        totexp = new javax.swing.JLabel();
        profitlbl = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Income & Expenditure Management");

        lgTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lgTime.setText("jLabel4");

        lgDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lgDate.setText("jLabel4");

        stringDay.setBackground(new java.awt.Color(0, 0, 0));
        stringDay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stringDay.setText("Date");

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/rsz_home.png"))); // NOI18N
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jPanel22.setBackground(new java.awt.Color(102, 211, 37));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lgDate, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(stringDay, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lgTime, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButton7)
                .addGap(9, 9, 9))
            .addComponent(jPanel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lgDate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stringDay, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lgTime))))
                .addGap(21, 21, 21)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        sdate11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        sdate12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setText("From");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setText("To");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setText("Income related to Sevices");

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Search_png.png"))); // NOI18N
        jButton10.setText("Search");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton10)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(95, 95, 95))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(110, 110, 110)))
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sdate11, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sdate12, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(61, 61, 61))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel25)
                .addGap(36, 36, 36)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(sdate12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(sdate11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnshowall1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnshowall1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/rsz_quickview-icon.png"))); // NOI18N
        btnshowall1.setText("Show all");
        btnshowall1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowall1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Expenditures");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Profit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Income Report");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnshowall1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(85, 85, 85)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnshowall1)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        incometbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        incometbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Receipt Id", "Job card ID", "Service Cost", "Item Cost", "Date"
            }
        ));
        jScrollPane6.setViewportView(incometbl);

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1201, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Income", jPanel4);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        sdate2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        sdate1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("From");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("To");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Expenditures Reated to Service Station");

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Search_png.png"))); // NOI18N
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(96, 96, 96)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sdate1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(sdate2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(61, 61, 61))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel10)
                .addGap(36, 36, 36)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(sdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(sdate2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Expenditure", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Type");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Description");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Amount");

        examount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        examount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                examountKeyPressed(evt);
            }
        });

        extype.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        extype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Electricity", "Water", "Salary", "Repair", "Other" }));

        exdescription.setColumns(20);
        exdescription.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exdescription.setRows(5);
        jScrollPane1.setViewportView(exdescription);

        exaddbutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exaddbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/rsz_add_big.png"))); // NOI18N
        exaddbutton.setText("Add");
        exaddbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exaddbuttonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Date");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Bill ID");

        expdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        exupdatebutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exupdatebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/rsz_update.png"))); // NOI18N
        exupdatebutton.setText("Update");
        exupdatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exupdatebuttonActionPerformed(evt);
            }
        });

        exdeletebutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exdeletebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/rsz_garbage_delete.png"))); // NOI18N
        exdeletebutton.setText("Delete");
        exdeletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exdeletebuttonActionPerformed(evt);
            }
        });

        exclear.setBackground(new java.awt.Color(255, 255, 255));
        exclear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exclear.setForeground(new java.awt.Color(255, 255, 255));
        exclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/rsz_images_1.jpg"))); // NOI18N
        exclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exclearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(exaddbutton))
                .addGap(76, 76, 76)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(exupdatebutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exdeletebutton)
                        .addGap(52, 52, 52))
                    .addComponent(expdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(extype, 0, 141, Short.MAX_VALUE)
                            .addComponent(examount)
                            .addComponent(exid, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exclear)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(exid)
                        .addComponent(jLabel7))
                    .addComponent(exclear, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(extype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(examount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(expdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exupdatebutton)
                    .addComponent(exaddbutton)
                    .addComponent(exdeletebutton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btninvenory.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btninvenory.setText("Inventory Expenses");
        btninvenory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninvenoryActionPerformed(evt);
            }
        });

        btnservice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnservice.setText("Service Expenses");
        btnservice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnserviceActionPerformed(evt);
            }
        });

        btnshowall.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnshowall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/rsz_quickview-icon.png"))); // NOI18N
        btnshowall.setText("Show all");
        btnshowall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowallActionPerformed(evt);
            }
        });

        jButton6.setText("Expenditure Report");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btninvenory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnservice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnshowall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(81, 81, 81)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnshowall)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addComponent(btninvenory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnservice)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        exptable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exptable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Bill ID", "Type", "Description", "Amount", "Date"
            }
        ));
        exptable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exptableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(exptable);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1196, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Service Expenses", jPanel15);

        invtable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        invtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Type", "Description", "Amount", "Date"
            }
        ));
        jScrollPane5.setViewportView(invtable);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1196, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 105, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Inventory Expenses", jPanel16);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Expenditures", jPanel8);

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        sdate9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        sdate10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("From");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("To");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("Profit For a Selected Period");

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/rsz_calculator_green.png"))); // NOI18N
        jButton9.setText("Calculate");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        cancelprofit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cancelprofit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/rsz_images_1.jpg"))); // NOI18N
        cancelprofit.setText("Cancel");
        cancelprofit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelprofitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGap(113, 113, 113)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(sdate9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sdate10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelprofit)))
                .addGap(22, 22, 22))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel22)
                .addGap(36, 36, 36)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(sdate10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sdate9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(cancelprofit))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Profit Calculator", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Total Income");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Total Expenditure");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Inventory Expenditures:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Miscellaneous Expenses:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Income from Services:");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel26.setText("Income from Items:");

        jobcostlbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jobcostlbl.setText("jLabel27");

        itemcostlbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        itemcostlbl.setText("jLabel28");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setText("Net Profit");

        totalincomelbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalincomelbl.setText("jLabel12");

        totexp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totexp.setText("jLabel16");

        profitlbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        profitlbl.setText("jLabel30");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("inv");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("jLabel18");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(127, 127, 127)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemcostlbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jobcostlbl, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jLabel11)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profitlbl)
                    .addComponent(totalincomelbl)
                    .addComponent(totexp))
                .addGap(186, 186, 186))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(totalincomelbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jobcostlbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(itemcostlbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(totexp))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(profitlbl))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 593, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(527, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Profit", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void exaddbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exaddbuttonActionPerformed
        exp_add();
    }//GEN-LAST:event_exaddbuttonActionPerformed

    private void exupdatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exupdatebuttonActionPerformed
       exp_update();
    }//GEN-LAST:event_exupdatebuttonActionPerformed

    private void exdeletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exdeletebuttonActionPerformed
        exp_delete();
    }//GEN-LAST:event_exdeletebuttonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        exp_search();   
    }//GEN-LAST:event_jButton4ActionPerformed

    private void exclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exclearActionPerformed
        // clear
        examount.setText("");
        exdescription.setText("");
        extype.setSelectedItem("");
        exid.setText("");
    }//GEN-LAST:event_exclearActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        profit_cal_fortime();        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // search
        income_search();
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void exptableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exptableMouseClicked
        // Table mouseclicked
        int r = exptable.getSelectedRow();

        String billid = exptable.getValueAt(r, 0).toString();
        String type = exptable.getValueAt(r, 1).toString();
        String description = exptable.getValueAt(r, 2).toString();
        String amount = exptable.getValueAt(r, 3).toString();
      

        exid.setText(billid);
        examount.setText(amount);
        exdescription.setText(description);
        extype.setSelectedItem(type);

        //expdate.setDate(date3);
    }//GEN-LAST:event_exptableMouseClicked

    private void btnshowallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowallActionPerformed
        // TODO add your handling code here:
        exp_showall();       
    }//GEN-LAST:event_btnshowallActionPerformed

    private void btninvenoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninvenoryActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(1);
        jPanel10.setVisible(false);
        btnservice.setVisible(true);
        btninvenory.setVisible(false);

    }//GEN-LAST:event_btninvenoryActionPerformed

    private void btnserviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnserviceActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(0);
        jPanel10.setVisible(true);
        btninvenory.setVisible(true);
        btnservice.setVisible(false);
        
    }//GEN-LAST:event_btnserviceActionPerformed

    private void btnshowall1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowall1ActionPerformed
        income_showall();
        
        
    }//GEN-LAST:event_btnshowall1ActionPerformed

    private void cancelprofitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelprofitActionPerformed
        // TODO add your handling code here:
        calprof();
        
    }//GEN-LAST:event_cancelprofitActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void examountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_examountKeyPressed
       //checkDouble(examount);
    }//GEN-LAST:event_examountKeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       try {
            
            String report = "C:\\Users\\chathura\\Documents\\NetBeansProjects\\voltage\\src\\reports\\income.jrxml";
            JasperReport jp = JasperCompileManager.compileReport(report);
            JasperPrint jd = JasperFillManager.fillReport(jp, null,conx);
            JasperViewer.viewReport(jd,false);
            
        } catch (Exception e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         try {
            
            String report = "C:\\Users\\chathura\\Documents\\NetBeansProjects\\voltage\\src\\reports\\report1.jrxml";
            JasperReport jp = JasperCompileManager.compileReport(report);
            JasperPrint jd = JasperFillManager.fillReport(jp, null,conx);
            JasperViewer.viewReport(jd,false);
            
        } catch (Exception e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       new voltage.Fdivision().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(exp_manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(exp_manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(exp_manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(exp_manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new exp_manage().setVisible(true);
            }
        });
    }
    
    
    

    /* 
    MY OWN METHODS CALLED    
    */
    
    
    public void tableload ()
    {
       try {
           
           
        exptable.setAutoCreateColumnsFromModel(false);
        invtable.setAutoCreateColumnsFromModel(false);
        incometbl.setAutoCreateColumnsFromModel(false);
                
       //table load Query
        //String sql = "SELECT billid,type,description,amount,date FROM bills";
        //String sql = "Select billid, type, description, amount, date from bills where date Between '"+ test +"' AND '"+ test1 +"'";            
        
        //Query for Expenditure
        String sql = "SELECT billid, type, description, amount, date from bills where date Between '"+ test1 +"' AND '"+ test +"' ORDER BY date ASC";
        pst = conx.prepareStatement(sql);
        rs = pst.executeQuery();
        exptable.setModel(DbUtils.resultSetToTableModel(rs));
        
        
        //Query for inventory
        String sql2 = "SELECT orderID, type, description, ordercost, date from order_item where date Between '"+ test1 +"' AND '"+ test +"' ORDER BY date ASC";
        pst = conx.prepareStatement(sql2);
        rs = pst.executeQuery();
        invtable.setModel(DbUtils.resultSetToTableModel(rs));
        
        
        //Query for Income
        String sql3 = "SELECT receiptID, jobCardID, job_cost, item_cost, date from receipt where date Between '"+ test1 +"' AND '"+ test +"' ORDER BY date ASC";
        pst = conx.prepareStatement(sql3);
        rs = pst.executeQuery();
        incometbl.setModel(DbUtils.resultSetToTableModel(rs));
        
        
        
        /*String sql2 = "Select orderID, type, description, ordercost,date from order_item where date Between '"+ test1 +"' AND '"+ test +"'";
        pst2=conx.prepareStatement(sql2);
        rs2= pst2.executeQuery();
        exptable.setModel(DbUtils.resultSetToTableModel(rs2));
        */
        
       
       }
       
       catch (Exception e){
       }
    }
    
    
    private void setDate(){
       // SimpleDateFormat dte = new SimpleDateFormat("YYY-MM-dd",Locale.getDefault());
       // lg_date.setText(dte);
        
        SimpleDateFormat dateFormatter = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat timeFormatter = new SimpleDateFormat("HH:mm:ss");
        java.util.Date today = Calendar.getInstance().getTime();
        String dateAsString = dateFormatter.format(today);
        String timeAsString = timeFormatter.format(today);
        lgTime.setText(timeAsString);
        lgDate.setText(dateAsString);
        
        java.util.Date now = new java.util.Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("EEEEEEEEE", Locale.US); 
        String asWeek = dateFormat.format(now);
        stringDay.setText(asWeek);
        //lg_date.setText(dateAsString);
    }
    
    
    
    // INCOME tab
    
    public void income_search(){
    SimpleDateFormat dte = new SimpleDateFormat("YYY-MM-dd",Locale.getDefault());
        String date1 = dte.format(sdate12.getDate());
        
        SimpleDateFormat dte2 = new SimpleDateFormat("YYY-MM-dd",Locale.getDefault());
        String date2 = dte2.format(sdate11.getDate());
        
        try {
            
             //Query for Income
        String sql3 = "SELECT receiptID, jobCardID, job_cost, item_cost, date from receipt where date Between '"+ date1 +"' AND '"+ date2 +"' ORDER BY date ASC";
        pst = conx.prepareStatement(sql3);
        rs = pst.executeQuery();
        incometbl.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        
        catch (Exception e){
        }
    }
    
      
    //get today
       public void currentDate(){
        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        month=month+1;
        int day = cal.get(Calendar.DAY_OF_MONTH);
        int year = cal.get(Calendar.YEAR);
        int dayone=1;
        
        String thisyear = String.valueOf(year);
        String thismonth = String.valueOf(month);
        String thisday = String.valueOf(day);
        String dayoneone = String.valueOf(dayone);
        
        test = ""+thisyear+"-0"+thismonth+"-"+thisday+"";
        test1= ""+thisyear+"-0"+thismonth+"-0"+dayoneone+"";
        System.out.println(test);
        System.out.println(test1);         
    }
              
       
    public void income_showall(){
    
        try{
        String sql = "SELECT receiptID, jobCardID, job_cost, item_cost, date from receipt ORDER BY date ASC";
        pst = conx.prepareStatement(sql);
        rs = pst.executeQuery();
        incometbl.setModel(DbUtils.resultSetToTableModel(rs));
        }
        
        catch(Exception e){
        }
    }  

    
    // expenditure  tab
    
    public void  exp_search(){
    // search
        SimpleDateFormat dte = new SimpleDateFormat("YYY-MM-dd",Locale.getDefault());
        String date1 = dte.format(sdate1.getDate());
        
        SimpleDateFormat dte2 = new SimpleDateFormat("YYY-MM-dd",Locale.getDefault());
        String date2 = dte2.format(sdate2.getDate());
        
        try {
            
            String sql = "Select billid, type, description, amount, date from bills where date Between '"+ date1 +"' AND '"+ date2 +"' ORDER BY date ASC" ;
            pst= conx.prepareStatement(sql);
            rs = pst.executeQuery();
            
            exptable.setModel(DbUtils.resultSetToTableModel(rs));
            
            
            //Query or inventory
            String sql2 = "SELECT orderID, type, description, ordercost, date from order_item where date Between '"+ date1 +"' AND '"+ date2 +"' ORDER BY date ASC";
            pst = conx.prepareStatement(sql2);
            rs = pst.executeQuery();
            invtable.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        }
        
        catch (Exception e){
        }
    }
    
    public void exp_showall(){
        SimpleDateFormat dte = new SimpleDateFormat("YYY-MM-dd",Locale.getDefault());
        String date1 = dte.format(sdate1.getDate());
        
        SimpleDateFormat dte2 = new SimpleDateFormat("YYY-MM-dd",Locale.getDefault());
        String date2 = dte2.format(sdate2.getDate());
        
        try {
            
            String sql = "Select billid, type, description, amount, date from bills ORDER BY date ASC" ;
            pst= conx.prepareStatement(sql);
            rs = pst.executeQuery();            
            exptable.setModel(DbUtils.resultSetToTableModel(rs));
            
            String sql2 = "SELECT orderID, type, description, ordercost, date from order_item ORDER BY date ASC";
            pst = conx.prepareStatement(sql2);
            rs = pst.executeQuery();
            invtable.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        }
        
        catch (Exception e){
        }
    }
    
    
    public void exp_add(){
    //add button
        String type = (String) extype.getSelectedItem();
        String amount1 = examount.getText();
        String description = exdescription.getText();
        
        SimpleDateFormat dte = new SimpleDateFormat("YYY-MM-dd",Locale.getDefault());
        String exp_date = dte.format(expdate.getDate());
                
        
        
   //table
        
        if(type.equals("") || description.equals("") || amount1.equals(""))
        {
            JOptionPane.showMessageDialog(null, "One or More Neccessary Field are Empty");
        }
        
        else {         
        try {
            Double amount = Double.parseDouble(amount1);
            String addquery = "Insert into bills ( type, amount, description, date) values ('"+ type +"', '"+ amount +"', '"+ description +"', '"+ exp_date +"')";
            pst = conx.prepareStatement(addquery);
            pst.execute();
            
            //load table refresh
            tableload();
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Amount field must be in numbers");           
            
        }
        
        }
        examount.setText("");
        exdescription.setText("");
        extype.setSelectedItem("");
        exid.setText("");
        //expdate.setDate(date3);
    }
    
    
    public void exp_update(){
    // TODO add your handling code here:
        
        int x =JOptionPane.showConfirmDialog(null, "Do you really want to update ?");
        
        if ( x ==0 ){
        
        String id = exid.getText();
        String type = (String) extype.getSelectedItem();
        String amount1 = examount.getText();
        String description = exdescription.getText();
        
        SimpleDateFormat dte = new SimpleDateFormat("YYY-MM-dd",Locale.getDefault());
        String exp_date = dte.format(expdate.getDate());
        
   //table
        
        if(type.equals("") || description.equals("") || amount1.equals(""))
        {
            JOptionPane.showMessageDialog(null, "One or More Neccessary Field are Empty");
        }
        
        else {         
        try {
            Double amount = Double.parseDouble(amount1);
            String addquery = "UPDATE bills set type ='"+ type +"', amount= '"+ amount +"', description='"+ description +"', date='"+ exp_date +"' where billid='"+id +"'";
            pst = conx.prepareStatement(addquery);
            pst.execute();
            
            //load table refresh
            tableload();
            
        } catch (SQLException ex) {
            
        }
        
        }
            
            
        }
        
        examount.setText("");
        exdescription.setText("");
        extype.setSelectedItem("");
        exid.setText("");
        //expdate.setDate(date3);
    }
    
    public void exp_delete(){
    int x =JOptionPane.showConfirmDialog(null, "Do you really want to Delete this ?");
        
        if ( x ==0 ){
            
            
            try {
                String id = exid.getText();
                String sq1 = "Delete from bills where billid='"+id +"'";
                pst = conx.prepareStatement(sq1);
                pst.execute();
                
                //table load
                tableload();
                
            } catch (SQLException ex) {
                Logger.getLogger(exp_manage.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
        examount.setText("");
        exdescription.setText("");
        extype.setSelectedItem("");
        exid.setText("");
        //expdate.setDate(date3);
    }
    
    
    // PROFIT tab
    
    
    //calculate profit     
    public void calprof(){
        
        try{
            
            // from bills table expenditure
            String sql3 = "select SUM(amount) AS Total from bills where date Between '"+ test1 +"' AND '"+ test +"'";
            pst = conx.prepareStatement(sql3);
            rs = pst.executeQuery();
            double totalamount=0;
            
            while(rs.next()){
            totalamount=rs.getDouble("Total");
             }
            
            System.out.println(totalamount);
            String totalamount1 = Double.toString(totalamount);
            jLabel18.setText(totalamount1);
            
            
            //from  order_item table expenditure
            String sql4 = "select SUM(ordercost) AS Totalorder from order_item where date Between '"+ test1 +"' AND '"+ test +"'";
            pst = conx.prepareStatement(sql4);
            rs = pst.executeQuery();
            double totalorder=0;
            
            while(rs.next()){
            totalorder=rs.getDouble("Totalorder");
             }
            
            
            String totalorder1 = Double.toString(totalorder);
            jLabel17.setText(totalorder1);
            
            double totalexp =(totalorder+totalamount);
            String totalexp1 = Double.toString(totalexp);
            totexp.setText(totalexp1);
            
            
            //income
            //income jobcostincome
             String sql5 = "select SUM(job_cost) AS jobcost from receipt where date Between '"+ test1 +"' AND '"+ test +"'";
            pst = conx.prepareStatement(sql5);
            rs = pst.executeQuery();
            double totaljobcost=0;
            
            while(rs.next()){
            totaljobcost=rs.getDouble("jobcost");
             }
            
            
            String totaljobcost1 = Double.toString(totaljobcost);
            jobcostlbl.setText(totaljobcost1);
            
            //income itemcostincome
            String sql6 = "select SUM(item_cost) AS itemcost from receipt where date Between '"+ test1 +"' AND '"+ test +"'";
            pst = conx.prepareStatement(sql6);
            rs = pst.executeQuery();
            double totalitemcost=0;
            
            while(rs.next()){
            totalitemcost=rs.getDouble("itemcost");
             }
            
            System.out.println(totaljobcost);
            String totalitemcost1 = Double.toString(totalitemcost);
            itemcostlbl.setText(totalitemcost1);
            
            
            double totalincome =(totaljobcost+totalitemcost);
            String totalincome1 = Double.toString(totalincome);
            totalincomelbl.setText(totalincome1);
                     
            
            //net profit count
            
            double profit=(totalincome-totalexp);
            String profit1 = Double.toString(profit);
            profitlbl.setText(profit1);
            
            Font font =new Font ("Tahoma", Font.BOLD,12);
            //Color colour = new Color(0,153,0);
            profitlbl.setFont(font);
                if (profit <= 0){
                    
                profitlbl.setForeground(Color.RED);
                }
                else{
                profitlbl.setForeground(Color.GREEN);
                }
            
            
            
            }
        catch (Exception e){}
    
    
    }
    
    
    public void profit_cal_fortime(){
    
        // Profit for a given time period
        
         try{
             
             
            SimpleDateFormat dte = new SimpleDateFormat("YYY-MM-dd",Locale.getDefault());
            String date1 = dte.format(sdate10.getDate());
        
            SimpleDateFormat dte2 = new SimpleDateFormat("YYY-MM-dd",Locale.getDefault());
            String date2 = dte2.format(sdate9.getDate());
            
            // from bills table expenditure
            String sql3 = "select SUM(amount) AS Total from bills where date Between '"+ date1 +"' AND '"+ date2 +"'";
            pst = conx.prepareStatement(sql3);
            rs = pst.executeQuery();
            double totalamount=0;
            
            while(rs.next()){
            totalamount=rs.getDouble("Total");
             }
            
            System.out.println(totalamount);
            String totalamount1 = Double.toString(totalamount);
            jLabel18.setText(totalamount1);
            
            
            //from  order_item table expenditure
            String sql4 = "select SUM(ordercost) AS Totalorder from order_item where date Between '"+ date1 +"' AND '"+ date2 +"'";
            pst = conx.prepareStatement(sql4);
            rs = pst.executeQuery();
            double totalorder=0;
            
            while(rs.next()){
            totalorder=rs.getDouble("Totalorder");
             }
            
            System.out.println(totalorder);
            String totalorder1 = Double.toString(totalorder);
            jLabel17.setText(totalorder1);
            
            double totalexp =(totalorder+totalamount);
            String totalexp1 = Double.toString(totalexp);
            totexp.setText(totalexp1);
            
            
            //income
            //income jobcostincome
             String sql5 = "select SUM(job_cost) AS jobcost from receipt where date Between '"+ date1 +"' AND '"+ date2 +"'";
            pst = conx.prepareStatement(sql5);
            rs = pst.executeQuery();
            double totaljobcost=0;
            
            while(rs.next()){
            totaljobcost=rs.getDouble("jobcost");
             }
            
            System.out.println(totaljobcost);
            String totaljobcost1 = Double.toString(totaljobcost);
            jobcostlbl.setText(totaljobcost1);
            
            //income itemcostincome
            String sql6 = "select SUM(item_cost) AS itemcost from receipt where date Between '"+ date1 +"' AND '"+ date2 +"'";
            pst = conx.prepareStatement(sql6);
            rs = pst.executeQuery();
            double totalitemcost=0;
            
            while(rs.next()){
            totalitemcost=rs.getDouble("itemcost");
             }
            
            System.out.println(totaljobcost);
            String totalitemcost1 = Double.toString(totalitemcost);
            itemcostlbl.setText(totalitemcost1);
            
            
            double totalincome =(totaljobcost+totalitemcost);
            String totalincome1 = Double.toString(totalincome);
            totalincomelbl.setText(totalincome1);
                     
            
            //net profit count
            
            double profit=(totalincome-totalexp);
            String profit1 = Double.toString(profit);
            profitlbl.setText(profit1);
            
            Font font =new Font ("Tahoma", Font.BOLD,12);
            //Color colour = new Color(0,153,0);
            profitlbl.setFont(font);
                if (profit <= 0){
                    
                profitlbl.setForeground(Color.RED);
                }
                else{
                profitlbl.setForeground(Color.GREEN);
                }
            
            
            }
        catch (Exception e){}
    }
    
    
    
    
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btninvenory;
    private javax.swing.JButton btnservice;
    private javax.swing.JButton btnshowall;
    private javax.swing.JButton btnshowall1;
    private javax.swing.JButton cancelprofit;
    private javax.swing.JButton exaddbutton;
    private javax.swing.JTextField examount;
    private javax.swing.JButton exclear;
    private javax.swing.JButton exdeletebutton;
    private javax.swing.JTextArea exdescription;
    private javax.swing.JLabel exid;
    private com.toedter.calendar.JDateChooser expdate;
    private javax.swing.JTable exptable;
    private javax.swing.JComboBox extype;
    private javax.swing.JButton exupdatebutton;
    private javax.swing.JTable incometbl;
    private javax.swing.JTable invtable;
    private javax.swing.JLabel itemcostlbl;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jobcostlbl;
    private javax.swing.JLabel lgDate;
    private javax.swing.JLabel lgTime;
    private javax.swing.JLabel profitlbl;
    private com.toedter.calendar.JDateChooser sdate1;
    private com.toedter.calendar.JDateChooser sdate10;
    private com.toedter.calendar.JDateChooser sdate11;
    private com.toedter.calendar.JDateChooser sdate12;
    private com.toedter.calendar.JDateChooser sdate2;
    private com.toedter.calendar.JDateChooser sdate9;
    private javax.swing.JLabel stringDay;
    private javax.swing.JLabel totalincomelbl;
    private javax.swing.JLabel totexp;
    // End of variables declaration//GEN-END:variables

    private void checkDouble(JTextField examount) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
